version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movie_tickets
    restart:
      always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d movie_tickets" ]
      interval: 5s
      timeout: 5s
      retries: 5

  db-init:
    build:
      context: ../
      dockerfile: devops/Dockerfile
    command: python -m backend.database.settings.__init__
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres+asyncpg://admin:admin@postgres/movie_tickets"

  backend:
    build:
      context: ../
      dockerfile: devops/Dockerfile
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    restart:
      always
    depends_on:
      - db-init
    environment:
      DATABASE_URL: "postgres+asyncpg://admin:admin@postgres/movie_tickets"


volumes:
  pgdata:
